// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SacramentMeeting.Models;

namespace SacramentMeeting.Migrations
{
    [DbContext(typeof(SacramentMeetingContext))]
    [Migration("20190407172618_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacramentMeeting.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Benediction");

                    b.Property<int>("ClosingHymn");

                    b.Property<string>("Conducting");

                    b.Property<string>("Invocation");

                    b.Property<DateTime>("MeetingDate");

                    b.Property<int>("OpeningHymn");

                    b.Property<string>("Presiding");

                    b.Property<int>("SacramentHymn");

                    b.Property<string>("Speaker1");

                    b.Property<string>("Speaker2");

                    b.Property<string>("Speaker3");

                    b.Property<string>("Topic1");

                    b.Property<string>("Topic2");

                    b.Property<string>("Topic3");

                    b.HasKey("Id");

                    b.ToTable("Meeting");
                });
#pragma warning restore 612, 618
        }
    }
}
